package corner.kjar;

import ftn.corner.model.*
import ftn.corner.model.PestAttribute
import java.util.ArrayList;


rule "startup"
    no-loop
    salience 999999999
    when
        $p: Object()
        not (PestRule())
    then
    	System.out.println("STARTUP RULE");

        ArrayList<PestAttribute> pa = new ArrayList<PestAttribute>();
        pa.add(PestAttribute.GRAY);
        pa.add(PestAttribute.INCH1);
        pa.add(PestAttribute.BUTTERFLY);
        pa.add(PestAttribute.ANTENA);
    	insert(new PestRule(Diagnoses.HELICOVERPA_ARMIGERA, pa));


        pa = new ArrayList<PestAttribute>();
        pa.add(PestAttribute.GRAY);
        pa.add(PestAttribute.INCH2);
        pa.add(PestAttribute.WORM);
        pa.add(PestAttribute.GOLD);
    	insert(new PestRule(Diagnoses.OSTRINIA_NUBILALIS, pa));

        pa = new ArrayList<PestAttribute>();
        pa.add(PestAttribute.BLACK);
        pa.add(PestAttribute.INCH1);
        pa.add(PestAttribute.LEGS8);
        pa.add(PestAttribute.ANTENA);
    	insert(new PestRule(Diagnoses.ELATERIDAE, pa));


        pa = new ArrayList<PestAttribute>();
        pa.add(PestAttribute.BLACK);
        pa.add(PestAttribute.GOLD);
        pa.add(PestAttribute.INCH1);
        pa.add(PestAttribute.LEGS6);
        pa.add(PestAttribute.ANTENA);
    	insert(new PestRule(Diagnoses.DIABROTICA_VIRGIFERA, pa));

        pa = new ArrayList<PestAttribute>();
        pa.add(PestAttribute.BLACK);
        pa.add(PestAttribute.GOLD);
        pa.add(PestAttribute.INCH2);
        pa.add(PestAttribute.LEGS6);
        pa.add(PestAttribute.ANTENA);
    	insert(new PestRule(Diagnoses.DIABROTICA_VIRGIFERA_IMAGO, pa));


        System.out.println("END OF STARTUP RULE");




end
