package corner.kjar;

import ftn.corner.model.User;
import ftn.corner.model.Plant;
import ftn.corner.model.PlantTypes;
import ftn.corner.model.GrowStages;
import ftn.corner.model.TreatmentHistory;
import ftn.corner.model.Treatment;

// rule "TestTest"
//     when
//         $i: User( name == "milos" )
//     then
//         $i.setName("IPPP Radi");
//         $i.setLastname("Petrovic");
//         update($i);
// end



 
// rule "Corn stages 1"
//     when
//         $c: Plant(plantType == PlantTypes.CORN, daysOld < 10)
//     then
//     	System.out.println("Pravilo jedaan");
//     	modify($c) {setGrowStage(GrowStages.GERMINATION)}
        
// end

// rule "Corn stages 2"
//     when
//         $c: Plant(plantType == PlantTypes.CORN, daysOld >= 10, daysOld < 20)
//     then
//     	System.out.println("");
//     	modify($c) {setGrowStage(GrowStages.LEAF_DEVELOPMENT)}
        
// end

// rule "Corn stages 3"
//     when
//         $c: Plant(plantType == PlantTypes.CORN, daysOld >= 20, daysOld < 30)
//     then
//     	System.out.println("");
//     	modify($c) {setGrowStage(GrowStages.TILLERING)}
        
// end

// rule "Corn stages 4"
//     when
//         $c: Plant(plantType == PlantTypes.CORN, daysOld >= 30, daysOld < 40)
//     then
//     	System.out.println("");
//     	modify($c) {setGrowStage(GrowStages.SHOOT_DEVELOPMENT)}
        
// end

// rule "Corn stages 5"
//     when
//         $c: Plant(plantType == PlantTypes.CORN, daysOld >= 40, daysOld < 50)
//     then
//     	System.out.println("");
//     	modify($c) {setGrowStage(GrowStages.BOLTING)}
        
// end

// rule "Corn stages 6"
//     when
//         $c: Plant(plantType == PlantTypes.CORN, daysOld >= 50, daysOld < 60)
//     then
//     	System.out.println("");
//     	modify($c) {setGrowStage(GrowStages.INFLORESCENCE)}
        
// end



rule "weed prevention 1"
    no-loop
    when
        $c: Plant(plantType == PlantTypes.CORN, growStage==GrowStages.GERMINATION)
    then
    	System.out.println("Add suggestion 2");

    	Treatment t = new Treatment(null, "Zastita od korova", "ZOK", "desc");
    	TreatmentHistory th = new TreatmentHistory();
    	th.setTreatment(t);

    	modify($c) {addTreatments(th)}

end
